import { useAppDispatch, useAppSelector } from '../app/hook'
import { Container, Heading } from '@chakra-ui/react'
import { formAction } from '../app/slice/formSlice'
import AddUserForm from '../container/AddUserForm'
import MyButton from '../components/ButtonForm'
import UserList from '../container/UserList'
import { AddIcon } from "@chakra-ui/icons"
import Head from 'next/head'

export default function Home() {
  const state = useAppSelector(state => state.form)
  const dispatch = useAppDispatch()

  const handelToggleForm = () => {
    dispatch(formAction.showForm())
  }
  return (
    <>
      <Head>
        <title>Actividad integradora 3. CRUD en Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="8xl" bg="whiteAlpha.300" paddingTop={'8'} >
        <Heading as="h2" size="2xl" textAlign="center">CRUD Next.JS</Heading>
        {
          state.toggleFormShow ? <AddUserForm /> :
            <MyButton
              onClick={handelToggleForm}
              leftIcon={<AddIcon />}
              colorScheme='green'>
              </MyButton>
        }
        <UserList />
        <div>
        <table>
          <tr>
            <th>Pablo</th>
            <th>Carmelo</th>
            <th>emin@gmail.com</th>
            <th>#4</th>
            <MyButton colorScheme='red'>del</MyButton> <MyButton colorScheme='blue'>edit</MyButton>
          </tr><br />
          <tr>
            <th>Juan</th>
            <th>López</th>
            <th>emrgrg@gmail.com</th>
            <th>#2</th>
            <MyButton colorScheme='red'>del</MyButton> <MyButton colorScheme='blue'>edit</MyButton>
          </tr><br />
          <tr>
            <th>Luis</th>
            <th>Jesus</th>
            <th>edwwn@gmail.com</th>
            <th>#1</th>
            <MyButton colorScheme='red'>del</MyButton> <MyButton colorScheme='blue'>edit</MyButton>
          </tr><br />
          <tr>
            <th>Maria</th>
            <th>Díaz</th>
            <th>frin@gmail.com</th>
            <th>#7</th>
            <MyButton colorScheme='red'>del</MyButton> <MyButton colorScheme='blue'>edit</MyButton>
          </tr><br />
          
          <tr>
            <th>Eduardo</th>
            <th>Flores</th>
            <th>egb@gmail.com</th>
            <th>#6</th>
            <MyButton colorScheme='red'>del</MyButton> <MyButton colorScheme='blue'>edit</MyButton>
          </tr><br />

          <tr>
            <th>Fran</th>
            <th>Hendz</th>
            <th>ghthdf@gmail.com</th>
            <th>#9</th>
            <MyButton colorScheme='red'>del</MyButton> <MyButton colorScheme='blue'>edit</MyButton>
          </tr><br />
          
        </table>
        </div>        
      </Container>
    </>
  )
}
